[en]
languageName = "English"
contentDir = "content"
weight = 10
[en.params]
languageISO = "EN"
languageTag = "en-US"
footer = '© Robert Winer, M.D., Dipl. (FAZ, Zürich), FRSM'
alertText = ''
