# Hugo
title = "Robert Winer, M.D., Dipl. (FAZ, Zürich), FRSM"
description = "Psychoanalysis and neuropsychiatric second opinion consultations in Boulder, CO."
images = ["cover.png"]

# mainSections
mainSections = ["blog"]

math = false
mathEngine = "KaTeX"

[social]
  twitter = ""

# Doks (@thulite/doks-core)
[doks]
  # Color mode
  colorMode = "auto"
  colorModeToggler = true

  # Navbar
  navbarSticky = true
  containerBreakpoint = "fluid"

  ## Button
  navBarButton = false
  navBarButtonUrl = "/second-opinions/"
  navBarButtonText = "Second Opinions"

  # FlexSearch
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = []
  showSearch = []
  indexSummary = false

  ## Search results
  showDate = false
  showSummary = true
  searchLimit = 99

  # Global alert
  alert = false
  alertDismissable = true

  # Bootstrap
  bootstrapJavascript = false

  # Nav
  sectionSwitcher = false
  sectionNav = ["blog"]
  toTopButton = false
  breadcrumbTrail = false
  headlineHash = true
  scrollSpy = true

  # Multilingual
  multilingualMode = false
  showMissingLanguages = true

  # Versioning
  docsVersioning = false
  docsVersion = "1.0"

  # UX
  headerBar = false
  backgroundDots = true
  aiButtons = false

  # Homepage
  sectionFooter = false

  # Blog
  relatedPosts = false
  imageList = true
  imageSingle = true

  # Repository
  editPage = false
  lastMod = false
  repoHost = "GitHub"
  docsRepo = "https://github.com/rwinermd/rwinermd-web"
  docsRepoBranch = "main"
  docsRepoSubPath = ""

  krokiURL = "https://kroki.io"

# Debug
[render_hooks.image]
  errorLevel = 'ignore'

[render_hooks.link]
  errorLevel = 'ignore'
  highlightBroken = false

# Images (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async"
    fetchpriority = "auto"
    loading = "lazy"
    widths = [480, 576, 768, 1025, 1200, 1440]
    sizes = "auto"
    process = ""
    lqip = "16x webp q20"

# Inline SVG (@thulite/inline-svg)
[inline_svg]
  iconSetDir = "tabler-icons"
  iconSetVariant = "outline"

# SEO (@thulite/seo)
[seo]
  [seo.title]
    separator = ""
    suffix = ""
  [seo.description]
    summaryFallback = ""
  [seo.favicons]
    icon = "favicon.png"
    svgIcon = "favicon.svg"
  [seo.schemas]
    type = "Person"
    logo = "favicon-512x512.png"
    name = "Robert Winer MD"
    sameAs = []
    images = ["cover.png"]
    article = []
    newsArticle = []
    blogPosting = ["blog"]
    product = []
